builds:
  - binary: xlsx-splitter
    main: ./cmd/main.go
    goos:
      - windows
      - darwin
      - linux
      - freebsd
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
    goarm:
      - '6'
    ignore:
      - goos: darwin
        goarch: '386'
    env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w # Don't set main.version.

gomod:
  proxy: false

archives:
  - name_template: "{{.Binary}}_{{.Os}}_{{.Arch}}"
    files:
      - README.md
      - completion/**/*
    format_overrides:
      - goos: windows
        format: zip

release:
  draft: false

snapshot:
  name_template: "{{.Tag}}"

checksum:
  name_template: "xlsx-splitter_checksums.txt"

nfpms:
  - vendor: xlsx-splitter
    homepage: https://github.com/crashmax-dev/xlsx-splitter
    maintainer: Vitalij Ryndin <crashmax.dev@gmail.com>
    description: Splits an XLSX file into multiple XLSX files
    license: MIT
    formats:
      - deb
      - rpm
    file_name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
    contents:
      - src: completion/bash/xlsx-splitter.bash
        dst: /etc/bash_completion.d/xlsx-splitter
      - src: completion/fish/xlsx-splitter.fish
        dst: /usr/share/fish/completions/xlsx-splitter.fish
      - src: completion/zsh/_xlsx-splitter
        dst: /usr/local/share/zsh/site-functions/_xlsx-splitter

brews:
  - name: xlsx-splitter
    description: Splits an XLSX file into multiple XLSX files
    license: MIT
    homepage: https://github.com/crashmax-dev/xlsx-splitter
    folder: Formula
    repository:
      owner: go-task
      name: homebrew-tap
    test:
      system "#{bin}/xlsx-splitter", "--help"
    install: |-
      bin.install "xlsx-splitter"
      bash_completion.install "completion/bash/xlsx-splitter.bash" => "xlsx-splitter"
      zsh_completion.install "completion/zsh/_xlsx-splitter" => "_xlsx-splitter"
      fish_completion.install "completion/fish/xlsx-splitter.fish"
    commit_author:
      name: crashmax-dev
      email: crashmax.dev@gmail.com
